name: Testing coverage
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Tests
        run: npm run test:ci
      - name: Generate coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: master
